### ISSUE TITLE
I'm guessing the release is compiled for windows only? 

### ISSUE THREAD

**Issue by ringofyre** [WoaowMusic/IndexSearchTool#1]
`$ java -jar -verbose:gc ~/Downloads/Index.Search.Tool.jar 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4926r21 in java.library.path
	no swt-win32 in java.library.path
	Can't load library: /home/rob/.swt/lib/linux/x86_64/libswt-win32-4926r21.so
	Can't load library: /home/rob/.swt/lib/linux/x86_64/libswt-win32.so

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:344)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:143)
	at com.github.woaowmusic.drsearch.index.Main.main(Main.java:47)
	... 5 more
`

on 

`$uname -a Linux Pavillion 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux`

I'll try building it.

**Comment by WoaowMusic** [comment]
Version 2 of the program has been released, and it now has binaries that are not platform-specific.  Please check the release notes.

Thank you for submitting the issue, and I apologize for the delay.

Open another issue if you have any other concerns.
